name 'formatron_common'
version '0.1.1'
description 'Formatron common cookbook'
source_url 'https://github.com/formatron/common-cookbook'
issues_url 'https://github.com/formatron/common-cookbook/issues'
depends 'formatron_packetbeat'
supports 'ubuntu'
depends 'apt'
depends 'build-essential'
depends 'formatron_filebeat'
depends 'formatron_sensu'
depends 'chef-client'
