name 'formatron_common'
version '0.1.6'
description 'Formatron common cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/common-cookbook'
issues_url 'https://github.com/formatron/common-cookbook/issues'
supports 'ubuntu'
depends 'apt'
depends 'build-essential'
depends 'formatron_filebeat'
depends 'formatron_sensu'
depends 'formatron_ntp'
depends 'chef-client'
